Frontend/main/__init__.py
import os
from flask import Flask
from dotenv import load_dotenv
from main.routes import routes

#Método que inicializará todos los módulos y devolverá la aplicación
def create_app():
    #Inicializar Flask
    app = Flask(__name__)
    #Cargar variables de entorno
    load_dotenv()
    app.config['API_URL'] = os.getenv('API_URL')
    app.register_blueprint(routes.app)
    #
    #Aquí se inicializarán el resto de los módulos de la aplicación
    #
    #Retornar aplicación inicializada
    return app

Frontend/main/routes/routes.py
from flask import Flask, Blueprint, current_app, render_template, make_response, request, redirect, url_for
import requests
import json

app = Blueprint('app', __name__, url_prefix='/')

@app.route('/')
def index():
     
    api_url = "http://127.0.0.1:6000/poemas"

    data = { "page": 1,"per_page" : 10 }
    

    headers = {"Content-Type" : "application/json"}

    response = requests.get(api_url, json=data, headers=headers)
    print(response)

    poemas = json.loads(response.text)
    print(poemas)
    return render_template('vista_principal.html', poemas=poemas['poemas'])


@app.route('/home')
def main():
    if request.cookies.get('access_token'):
        data = { "page": 1, "per_page": 5 }
        if 'page' in request.args:
            data["page"] = request.args.get('page', '')
        api_url = f'{current_app.config["API_URL"]}/poemas' 
        headers = { "Content-Type": "application/json" }
        response = requests.get(api_url, json=data, headers=headers)
        poems = json.loads(response.text)
        pagination = {}
        pagination["pages"] = json.loads(response.text)["pages"]
        pagination["current_page"] = json.loads(response.text)["page"]
        return render_template('vista_principal.html', poemas=poemas["poemas"], pagination=pagination)  
         
    else:
        return redirect(url_for('app.login'))
@app.route('/perfil')
def perfil():
    return render_template('mi_perfil.html')

@app.route('/view-poem/<int:id>', methods=['GET'])
def view_poem(id):
    api_url = f'{current_app.config["API_URL"]}/poema/{id}'
    print("aca esta el", id)
    jwt = request.cookies.get("access_token")
    headers = {f"Content-Type" : "application/json", "Authorization" : "Bearer {}".format(jwt)}
    response = requests.get(api_url, headers=headers)
    poema = json.loads(response.text)
    print(poema)
    return render_template('ver_poema.html', poema = poema)

@app.route('/upload-poem', methods=['GET', 'POST'])
def upload_poem():
    jwt = request.cookies.get("access_token")
    if request.cookies.get('access_token'):
        print("hola")
        if request.method == 'POST':
            titulo = request.form['titulo']
            cuerpo = request.form['cuerpo']
            print(titulo)
            print(cuerpo)
            print(jwt)
            usuarioid = request.cookies.get("id")
            print(usuarioid)
            data = {"usuarioid": usuarioid, "titulo": titulo, "cuerpo": cuerpo}
            headers = {"Content-Type" : "application/json", "Authorization": f"Bearer {jwt}"}
            if titulo != "" and cuerpo != "":
                response = requests.post(f'{current_app.config["API_URL"]}/poemas', json=data, headers=headers)
                if response.ok:
                    response = json.loads(response.text)
                    print(response)
                    return redirect(url_for('app.index'))
                else:
                    return redirect(url_for('app.upload_poem'))
            else:
                return redirect(url_for('app.upload_poem'))
        else:
            return render_template('subir_poema.html', jwt=jwt) 
    else:
        return redirect(url_for('app.login'))

@app.route('/login', methods=['GET','POST'])
def login():
    if (request.method == 'POST'):
        #obtener datos del formulario - Esto lo traigo del HTML con los name de los inputs. 
        email = request.form['email']
        contraseña = request.form['contraseña']
        print(email, contraseña)

        if email != None and contraseña != None: 
            #es la url que utilizamos en insomnia
            api_url = f'{current_app.config["API_URL"]}/auth/login'
            #Envio de token
            data = {"email" : email, "contraseña" : contraseña}
            headers = {"Content-Type" : "application/json"}
            response = requests.post(api_url, json = data, headers = headers) 
            print("login", response)
            if (response.ok): 

                response = json.loads(response.text)
                token = response["access_token"]
                usuarioid = str(response["id"])

                #Guardar el token en las cookies y devuelve la pagina 
                response = make_response(redirect(url_for('app.index')))
                #response = make_response(user_main(jwt=token)) 
                response.set_cookie("access_token", token)
                response.set_cookie("id", usuarioid)
                return response
                #return render_template('login.html')
        return(render_template('inicio_sesion.html', error = "Usuario o contraseña incorrectos"))
    else:
        return render_template('inicio_sesion.html')
    """if request.method == 'POST':
        email= request.form['email']
        contraseña= request.form['contraseña']
        print(email)
        print(contraseña)

        api_url = "http://127.0.0.1:6000/auth/login"

        data = {"email": "danilos@mail.com", "contraseña": "1234"}

        headers = {"Content-Type": "application/json"}

        response = requests.post(api_url, json=data, headers=headers)
        if response.status_code == 200:

            print(response.status_code)
            print(response.text)

            token = json.loads(response.text)
            token = token["access_token"]
            print(token)

            resp = make_response(redirect(url_for('app.index')))
            resp.set_cookie("access_token", token)
            return resp
        else:
            return render_template('inicio_sesion.html')
    return render_template('inicio_sesion.html')"""
@app.route('/user-poems')
def user_poems():

    api_url = "http://127.0.0.1:6000/poemas"

    data = {"page": 1, "per_page": 5}

    jwt = request.cookies.get("access_token")
    print(jwt)

    headers = {"Content-Type": "application/json", "Authorization": "Bearer {}".format(jwt)}

    response = requests.get(api_url, json=data, headers=headers)

    print(response.status_code)

    poemas = json.loads(response.text)

    poemas = poemas["poemas"]

    return render_template('mis_poemas.html', jwt = jwt, poemas = poemas)

@app.route('/qualify')
def qualify():
    return render_template('calificar_poema.html')

@app.route('/add-user')
def add_user():
    return render_template('añadir_usuario.html')


@app.route('/logout')
def logout():
    #Crear una request de redirección
    req = make_response(redirect(url_for('app.login')))
    #Borrar cookie
    req.delete_cookie("access_token")
    req.delete_cookie("id")
    return req

"""@app.route('/poem/<int:id>/delete')
def delete_poem(id):
    if request.cookies.get('accsess_token'):
        api_url = f'{current_app.config["API_URL"]}/poema/{id}'
        headers = {"Content-Type" : "application/json"}
        response = requests.delete(api_url, headers=headers)
        return response"""

@app.route('/main-user')
def user_main():
    jwt = request.cookies.get("access_token") 
    if jwt:

        api_url = "http://127.0.0.1:6000/poemas"

        data = { "page": 1,"per_page" : 10 }
    
        jwt = request.cookies.get("access_token")

        headers = {"Content-Type" : "application/json", "Authorization":"Bearer {}".format(jwt)}
        print (jwt)

        response = requests.get(api_url, json=data, headers=headers)
        print(response.status_code)
        print(response.text)

        poemas = json.loads(response.text)
        print (poemas)

        return render_template('vista_principal.html', poemas = poemas['poemas'])

Frontend/main/templates/añadir_usuario.html
{% extends "base.html" %}
  {% block content %}
    <body class="bg-primary">
    
    <div class="container">
                    <div class="d-flex justify-content-center bg-primary">
                        <i class="bi bi-person-plus-fill"></i>
                        <h3>Añadir Usuario</h3>
                    </div>
                    <div class="d-flex justify-content-center mt-4">
                        <div class="col-md-4 bg-light p-4 rounded ">
                            <form>
                                <div class="mb-3">
                                    <i class="bi bi-person-check-fill"></i>

                                  <label for="exampleInputEmail1" class="form-label">Alias</label>
                                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                </div>
                                <div class="mb-3">
                                    <i class="bi bi-envelope-plus"></i>
                                      <label for="exampleInputEmail1" class="form-label">Email</label>
                                      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                    </div>
                                    
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Añadir Usuario</button>
                    </div>
                  </form>
                  
            </div>
        </div>
    
 
    </div>
    
{% endblock %}

Frontend/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles.css">
    {% endblock %}
    
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <i class="bi bi-journal-arrow-up"></i>
        <a href="{{url_for('app.index')}}" class="navbar-brand">PoemsLooks</a>
        <i class="fa-solid fa-book"></i>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-list-ul"></i>
              </a>
              <ul class="dropdown-menu my-3" aria-labelledby="navbarDropdown">
                <li>

                    <a class="dropdown-item d-grid" href="{{url_for('app.perfil')}}">
                        <div class="btn btn-info" href="{{url_for('app.perfil')}}">Editar perfil</div>
                    </a>


                  </li>
                <li>
                    <a class="dropdown-item d-grid" href="{{url_for('app.user_poems')}}">
                      <div class="btn btn-warning">Mis Poemas</div>
                    </a>
                  </li>
                  <li>
                    <a class="dropdown-item d-grid" href="{{url_for('app.upload_poem')}}">
                      <div class="btn btn-success">Crear Poema</div>
                    </a>
                  </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                    <a class="dropdown-item d-grid" href="{{url_for('app.logout')}}">
                      <div class="btn btn-danger" href="{{url_for('app.logout')}}">Cerrar sesion</div>
                    </a>
                  </li>
              </ul>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="#">Poeta@mail.com</a>
            </li>
            <li class="nav-item">
          </ul>
        </div>
      </div>
    </nav>

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block scripts %}
     <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/fe4eb8c452.js" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

    -->
    {% endblock %}
</body>
</html>

Frontend/main/templates/calificar_poema.html
{% extends "base.html" %}
  {% block content %}
    <body class="bg-primary">
    
    <div class="container">
                    <div class="d-flex justify-content-center bg-primary">
                        <i class="bi bi-arrow-up-circle"></i>
                        <h3>Calificar Poema</h3>
                    </div>
                    <div class="d-flex justify-content-center mt-4">
                        <div class="col-md-4 bg-light p-4 rounded ">
                            <form>
                                <div class="mb-3">
                                    <i class="bi bi-graph-up-arrow"></i>
                                    <label for="customRange2" class="form-label"> Rango de Calificacion</label>
                                    <input type="range" class="form-range" min="0" max="10" id="customRange2">
                                      </div>
    
                                <div class="mb-3">
                                    <i class="bi bi-chat-right"></i>
                                          <label for="exampleInputEmail1" class="form-label">Comentario</label>
                                          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                        </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Calificar Poema</button>
                    </div>
                  </form>
                  
            </div>
        </div>
    
 
    </div>
  {% endblock %}  

Frontend/main/templates/inicio_sesion.html
{% extends "base.html" %}
    
    {% block content %}
    <body class="bg-info">

    <div class="container">
        <div class="d-flex justify-content-center bg-info">
            <h3>Inicia sesion</h3>
        </div>
        <div class="d-flex justify-content-center mt-4">
            <div class="col-md-4 bg-light p-4 rounded ">
                
                  <form class="pt-3" method="POST" action="/login">
                    <div class="mb-3">
                      <i class="far fa-envelope"></i>
                      <label for="exampleInputEmail1" class="form-label">INDICA TU EMAIL</label>
                      <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                      <div id="emailHelp" class="form-text">No compartiremos tu email con nadie</div> 
                      
                    </div>
                    <div class="mb-3">
                      <i class="fas fa-key"></i>
                      <label for="exampleInputPassword1" class="form-label">INDICA TU CONTRASEÑA</label>
                      <input name="contraseña" type="password" class="form-control" id="exampleInputPassword1">
                      
                    </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Verificar</label>
        </div>
      
      <div class="btn-group d-flex justify-content-center bg-primary mt-4" role="group" aria-label="Basic example">
        <button type="submit">Iniciar sesion</button>
        </div>
      </form>
      <div class="btn-group d-flex justify-content-center bg-primary mt-4" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-primary">¿Olvidaste tu contraseña?</button>
     
       
  </div>
  </div>
  
  {% endblock %}
 

Frontend/main/templates/mi_perfil.html
{% extends "base.html" %}
   
  {% block content %}
    <body class="bg-secondary">
        
            <div class="container">
				<div class="d-flex justify-content-center bg-secondary">
          <i class="bi bi-person-fill bg"></i>
					<h3>Perfil</h3>
				</div>
            
            
                <ol class="list-group list-group-numbered">
                    <li class="list-group-item d-flex justify-content-between align-items-start"> 
                      <div class="ms-2 me-auto"> 
                        <div class="fw-bold">Nombre</div> 
                        anon232112
                      </div>
                      
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                      <div class="ms-2 me-auto ">
                        <div class="fw-bold">Email</div>
                        user@mail.com
                      </div>
                      
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                      <div class="ms-2 me-auto">
                        <div class="fw-bold">Password</div>
                        **********
                      </div>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">Poemas</div>
                          #Number
                        </div>
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">Calificaciones</div>
                              #Number
                            </div>
                      
                    </li>
                  </ol>

                  <div class="btn-group d-flex justify-content-center bg-primary g-col-6">
                    <button class="btn btn-danger" type="button">Eliminar cuenta</button>
                    <button class="btn btn-primary" type="button">Modificar dato</button>
                  </div>

  {% endblock %}

    

   

Frontend/main/templates/mis_poemas.html
{% extends "base.html" %}
    
    {% block content %}
    <body class="bg-light">
<div class="container"></div>
<div class="d-flex justify-content-center bg-primary">
    <h3>Mis Poemas</h3>
    <i class="bi bi-book-half"></i>
   
</div>

</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Titulo</th>
      <th scope="col">Cuerpo</th>
      <th scope="col">Fecha</th>
    </tr>
  </thead>
  {% for poema in poemas %}
  <tbody>
    <tr>
      <th scope="row">{{poema.id}}</th>
      <td>{{poema.titulo}}</td>
      <td>{{poema.cuerpo}}</td>
      <td>{{poema.fecha_hora}}</td>
    </tr>
    
    </tr>
  {% endfor %}
  </tbody>
</table>
<div class="d-flex justify-content-around mt-4">
    <button class="btn btn-primary" >Editar</button>
    <a class="btn btn-success" type ="button" href="{{url_for('app.upload_poem')}}">Subir Poema</a>
  </div>

  {% endblock %}
 

Frontend/main/templates/subir_poema.html
{% extends "base.html" %}
  {% block content %}
    <body class="bg-info">
    
    <div class="container">
                    <div class="d-flex justify-content-center bg-info">
                        <i class="bi bi-arrow-up-circle"></i>
                        <h3>Subir Poema</h3>
                    </div>
                    <div class="d-flex justify-content-center mt-4">
                        <div class="col-md-4 bg-light p-4 rounded ">
                            <form method="POST" action="/upload-poem">
                                <div class="mb-3">
                                    <i class="bi bi-pencil"></i>

                                  <label class="form-label">Titulo</label>
                                  <input type="titulo" class="form-control" name="titulo" aria-describedby="emailHelp">
                                </div>
                                <div class="mb-3">
                                    <i class="bi bi-person-square"></i>
                                      <label  class="form-label">Autor</label>
                                      <input type="autor" class="form-control" name="usuario"  aria-describedby="emailHelp">
                                    </div>
                                    <div class="mb-3">
                                        <i class="bi bi-body-text"></i>
                                          <label  class="form-label">Cuerpo</label>
                                          <input  class="form-control" name="cuerpo" aria-describedby="emailHelp">
                                        </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Añadir Poema</button>
                    </div>
                  </form>
                  
            </div>
        </div>
    
 
    </div>
    
  {% endblock %}

Frontend/main/templates/ver_poema.html
{% extends "base.html" %}
  {% block content %}  
    <body class="bg-secondary">
    
    <div class="container">

      <div class="d-flex justify-content-center bg-primary">
        <i class="bi bi-spellcheck bg-4"></i>
        <h3>Detalles del poema</h3>
      </div>
      
      <div class="col-md-4">
        <div class="card">
          <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
          <div class="d-grid gap-2">
            <h5 class="card-title">Titulo:{{poema.titulo}}</h5>
            <h5 class="card-title">Autor:{{poema.usuario.nombre}}</h5>
            <h5 class="card-title">Cuerpo:{{poema.cuerpo}}</h5>
            <h5 class="card-title">Fecha de creacion:{{poema.fecha_hora}}</h5>
            <div class="d-grid gap-2">
              <a href="{{url_for('app.qualify')}}" class="btn btn-success">Calificar Poema</a>
              <button class="btn btn-warning" type="button">Eliminar Poema</button>
           </div>
                     </div>
                     </div>
        </div>
       
  {% endblock %}
      
  

  

Frontend/main/templates/vista_principal.html
{% extends "base.html" %}
  
    {% block content %}

    <body class="bg-light">

    <div class="container">

        <div class="d-flex justify-content-center bg-primary">
        
        <i class="bi bi-book"></i>
          <h3>Poemas Para Ver</h3>
        </div>
        <div class = "row"> 
          {% for poema in poemas %}
        <div class="col-md-4">
          <div class="card">
            <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
            <div class="d-grid gap-2">
              <h5 class="card-title">{{poema.titulo}}</h5>
              <h5 class="card-title">{{poema.cuerpo}}</h5>
              <a href="{{url_for('app.view_poem', id=poema.id)}}" class="btn btn-primary">Ver Poema</a>
              
             </div>
             </div>
          </div>
         {% endfor %}
                  
          <div class="btn-toolbar d-flex justify-content-center " role="toolbar" aria-label="Toolbar with button groups" style= "width:100%">
            <div class="btn-group me-4" role="group" aria-label="First group">
              <button type="button" class="btn btn-primary" style="margin: 0 7px">1</button>
              <button type="button" class="btn btn-primary" style="margin: 0 7px">2</button>
              <button type="button" class="btn btn-primary" style="margin: 0 7px">3</button>
              <button type="button" class="btn btn-primary"style="margin: 0 7px">4</button>
              <button type="button" class="btn btn-primary"style="margin: 0 7px">5</button>
              <button type="button" class="btn btn-primary" style="margin: 0 7px">6</button>
              <button type="button" class="btn btn-primary" style="margin: 0 7px">...</button>
            </div>
          </div>
        {% endblock %}
         
         <!-- <div class="col-md-4">
            <div class="card">
              <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
              <div class="d-grid gap-2">
                <h5 class="card-title">Nombre Poema</h5>
                <h5 class="card-title">Promedio Puntaje</h5>
                <a href="#" class="btn btn-primary">Ver Poema</a>
               </div>
               </div>
         </div>
         <div class="col-md-4">
            <div class="card">
              <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
              <div class="d-grid gap-2">
                <h5 class="card-title">Nombre Poema</h5>
                <h5 class="card-title">Promedio Puntaje</h5>
                <a href="#" class="btn btn-primary">Ver Poema</a>
                <div class="d-grid gap-2">
                    
               </div>
               </div>
               </div>""""""
         </div>
         
         <div class="col-md-4">
            <div class="card">
              <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
              <div class="d-grid gap-2">
                <h5 class="card-title">Nombre Poema</h5>
                <h5 class="card-title">Promedio Puntaje</h5>
                <a href="#" class="btn btn-primary">Ver Poema</a>
                <div class="d-grid gap-2">
                    
               </div>
               </div>
               </div>
         </div>

         <div class="col-md-4">
            <div class="card">
              <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
              <div class="d-grid gap-2">
                <h5 class="card-title">Nombre Poema</h5>
                <h5 class="card-title">Promedio Puntaje</h5>
                <a href="#" class="btn btn-primary">Ver Poema</a>
                <div class="d-grid gap-2">
                    
               </div>
               </div>
               </div>
         </div>
  
         <div class="col-md-4">
            <div class="card">
              <img src="https://via.placeholder.com/100x100" class="card-img-top" alt="...">
              <div class="d-grid gap-2">
                <h5 class="card-title">Nombre Poema</h5>
                <h5 class="card-title">Promedio Puntaje</h5>
                <a href="#" class="btn btn-primary">Ver Poema</a>
                <div class="d-grid gap-2">
                    
               </div>
               </div>
               </div>
         </div>
  
  
    </div>
   -->
 